export interface IUser {
    id: string,
    firstname: string,
    lastname: string,
    email: string,
    phone_code: string | null,
    phone: string | null,
    avatar: string | null,
    address: string | null,
    country: string | null,
    state: string | null,
    email_verified_at: string | null,
    two_factor_enabled_at: string | null,
    last_login_at: string | null,
    last_login_ip_address: string | null,
    blacklisted_at: string | null,
    status: string,
    auth_type: string,
    type: string,
    ref_code: string | null,
    created_at: string,
    updated_at: string,
    deleted_at: string
}